[package]
name = "ejercicio1"
version = "0.1.0"
edition = "2021"
include = ["data/input.txt"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]